[tfchain]
version = "2.8.1"
repo = "https://github.com/threefoldtech/tfchain"

[[tfchain.services.node]]
version = ">=2.7.0"
path="substrate-node"

[[tfchain.services.bridge]]
version = ">=2.7.0"
path="bridge"

[[tfchain.services.activationservice]]
version = ">=2.7.0"
path="activation-service"

[tfchain_client_js]
version = ">=2.7.0"
repo = "https://github.com/threefoldtech/tfchain"

[tfchain_graphql]
version = "2.12.1"
repo = "https://github.com/threefoldtech/tfchain_graphql"

[zos]
version = "3.10.6"
repo = "https://github.com/threefoldtech/zos"

[tfgrid-sdk-go]
version = "0.15.5"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"

[gridproxy]
version = "0.15.7"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"

[relay-cache-warmer]
version = "0.15.5"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"


[farmerbot]
version = "0.15.5"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"

[terraform]
version = "1.11.0"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"


[pulumi]
version = "0.6.4"
repo = "https://github.com/threefoldtech/pulumi-threefold"

[tfgrid-sdk-ts]
version = "2.4.3"
repo = "https://github.com/threefoldtech/tfgrid-sdk-ts"
[[tfgrid-sdk-ts.services.dashboard]]
path="packages/dashboard"
[[tfgrid-sdk-ts.services.stats]]
path="packages/stats"

[rmb]
version="1.3.0"
repo="https://github.com/threefoldtech/rmb-rs"
