[tfchain]
version = ">=2.9.2"
repo = "https://github.com/threefoldtech/tfchain"

[[tfchain.services.node]]
version = ">=2.9.2"
path="substrate-node"

[[tfchain.services.bridge]]
version = "2.9.2"
path="bridge"

[[tfchain.services.activationservice]]
version = ">=2.7.0"
path="activation-service"

[tfchain_client_js]
version = ">=2.7.0"
repo = "https://github.com/threefoldtech/tfchain"

[tfchain_graphql]
version = "2.12.2"
repo = "https://github.com/threefoldtech/tfchain_graphql"

[zos]
version = "3.13.0"
repo = "https://github.com/threefoldtech/zos"

[zoslight]
version = "0.3.0"
repo = "https://github.com/threefoldtech/zoslight"

[mycelium]
version = "1.0.0"
repo = "https://github.com/threefoldtech/mycelium"

[tfgrid-sdk-go]
version = "0.16.1"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"

[gridproxy]
version = "0.16.5"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"

[farmerbot]
version = "0.16.0"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"

[terraform]
version = "1.11.2"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"


[pulumi]
version = "0.8.1"
repo = "https://github.com/threefoldtech/pulumi-threefold"

[tfgrid-sdk-ts]
version = "2.7.0"
repo = "https://github.com/threefoldtech/tfgrid-sdk-ts"
[[tfgrid-sdk-ts.services.dashboard]]
path="packages/dashboard"
[[tfgrid-sdk-ts.services.stats]]
path="packages/stats"

[rmb]
version="1.3.3"
repo="https://github.com/threefoldtech/rmb-rs"


[tf-kyc-verifier]
version="0.2.2"
repo="https://github.com/threefoldtech/tf-kyc-verifier/"


[threefold-connect]
version = "4.2.2"
repo = "https://github.com/threefoldtech/threefold_connect"
