[tfchain]
version = "2.4.0"
repo = "https://github.com/threefoldtech/tfchain"

[tfchain_client_js]
version = "2.4.0"
repo = "https://github.com/threefoldtech/tfchain"

[tfchain_graphl]
version = "2.9.2"
repo = "https://github.com/threefoldtech/tfchain_graphql"

[zos]
version = "3.7.0"
repo = "https://github.com/threefoldtech/zos"

[tfgrid-sdk-go]
version = "0.8.5"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"

[terraform]
version = "1.9.1"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"

[gridproxy]
version = "0.8.5"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"

[tfgrid-sdk-ts]
version = "2.0.0"
repo = "https://github.com/threefoldtech/tfgrid-sdk-ts"
