[zos]
version = "4.0.0"
repo = "https://github.com/threefoldtech/zos4"


[mycelium]
version = "1.0.0"
repo = "https://github.com/threefoldtech/mycelium"

[registrar]  ## to be moved to v4 monorepo
version = "0.0.1"
repo = "https://github.com/threefoldtech/tfgrid-sdk-go"


[rmb]
version="1.3.2"
repo="https://github.com/threefoldtech/rmb-rs"

